### ISSUE TITLE
[BUG] Registration Warped Incorrectly with Princeton Mouse Brain Atlas

### ISSUE THREAD

**Issue by samclothier** [brainglobe/brainreg#95] opened 2022-09-13 10:38 UTC
**Describe the bug**
I successfully registered the new Princeton mouse brain atlas to our data (1st image), but the output file corresponding to our atlas-registered data appears to have a warped transformation that is misaligned to the atlas (2,3), when using the same command on the same data with the Allen atlas works without issue (4). This issue arises with all datasets tried (currently two).

**To Reproduce**
Run the following command in the terminal:
`brainreg stackDir outputDir -v 5 2 2 --orientation psr --atlas princeton_mouse_20um --n-free-cpus 1`
Brainreg executes successfully, but results in data misaligned to the standard atlas.

**Expected behaviour**
Brainreg successful registration of both the atlas to the data (successful), but most important is registration of the data to the atlas (unsuccessful) for transformation of cell position coordinates into atlas space.

**Log file**
[brainreg_2022-09-06_13-38-00.log](https://github.com/brainglobe/brainreg/files/9556069/brainreg_2022-09-06_13-38-00.log)

**Screenshots**
![image 1](https://user-images.githubusercontent.com/5054094/189880337-d8fedb94-eb49-4869-9eab-c2268903c7d8.png)
![image 2](https://user-images.githubusercontent.com/5054094/189880358-05b3c7e9-a1ca-421a-b483-4f0dc3829d75.png)
![image 3](https://user-images.githubusercontent.com/5054094/189880372-4f689df7-48e0-47b9-bc20-2a3af6fa70db.png)
![image 4](https://user-images.githubusercontent.com/5054094/189880386-7f90f4c8-a535-40f9-b5e7-04d2060dcbf7.png)

**Desktop (please complete the following information):**
- OS: Windows
- Version: 21H2
- Hardware specs: 64 GB RAM, Intel Core i5-6600 CPU @ 3.30GHz

**Additional context**
We just added the Princeton mouse brain atlas to BrainGlobe, and this bug appears to happen only for this new atlas.

**Comment by adamltyson** [comment] 2023-11-24 16:40
Hi @samclothier I don't suppose you got anywhere with this issue?

**Comment by samclothier** [comment] 2023-12-05 13:11
Hi @adamltyson, unfortunately we didn't figure this out and ended up sticking with the Allen atlas.

**Comment by adamltyson** [comment] 2024-09-12 10:53
I think this is due to the differing template images. It's not a bug as much as the registration not performing as well with this other atlas. 

I've tested registration against the princeton and the allen atlas. Both work, but in some cases one is a better choice than others. I'm going to close this issue, but let us know if you have any further problems @samclothier.

**Closed by adamltyson** 2024-09-12 10:53 UTC
Labels: bug
