### ISSUE TITLE
pip install brainreg fails on M2 processor (macOS Monterey)

### ISSUE THREAD

**Issue by JoeZiminski** [brainglobe/brainreg#90] opened 2022-08-26 10:02 UTC
**Describe the bug**
pip install brainreg fails on macOS M2 processor OS Monetary.

This appears to be due to issue with HDF5 dependency of the tables dependency (see traceback below). This is discussed [here](https://github.com/PyTables/PyTables/issues/832) with a solution provided [here](https://github.com/NOAA-OWP/hydrotools/issues/198).

The solution to install PyTables pointing to a HDF5 installation (e.g. brew install HDF5):

```
HDF5_DIR=/opt/homebrew/opt/hdf5 pip install tables
```

It might be worth having a note somewhere on installation instructions?

Traceback:

```
Collecting tables
  Using cached tables-3.7.0.tar.gz (8.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      /var/folders/3y/1rydgtw509jc23z5b_d59_fm0000gn/T/H5closeliddlhq7.c:2:5: error: implicit declaration of function 'H5close' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
          H5close();
          ^
      1 error generated.
      cpuinfo failed, assuming no CPU features: No module named 'cpuinfo'
      * Using Python 3.9.12 (main, Jun  1 2022, 06:34:44)
      * Found cython 0.29.32
      * USE_PKGCONFIG: False
      * Found conda env: ``/opt/homebrew/anaconda3/envs/general``
      .. ERROR:: Could not find a local HDF5 installation.
         You may need to explicitly state where your local HDF5 headers and
         library can be found by setting the ``HDF5_DIR`` environment
         variable or by using the ``--hdf5`` command-line option.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by JoeZiminski** [comment] 2022-08-26 10:26
*Have just seen macOS is not supported at present

**Comment by adamltyson** [comment] 2022-08-26 10:35
Going to close this as a duplicate of https://github.com/brainglobe/brainreg/issues/77. I think this should be a priority now though. As NiftyReg (registration backend) is on conda, we should be able to create a conda recipe to get everything up and running on macOS. 

It would be worth testing whether brainreg can run in a container on macOS for now.

**Closed by adamltyson** 2022-08-26 10:35 UTC
Labels: bug
